using System;
using System.Collections.Generic;

namespace FinalProject_Recipes.Models
{
    public partial class Diets
    {
        public Diets()
        {
            AspNetUsers = new HashSet<AspNetUsers>();
        }

        public string Id { get; set; }
        public string Ingredient1 { get; set; }
        public string Ingredient2 { get; set; }
        public string Ingredient3 { get; set; }
        public string Ingredient4 { get; set; }
        public string Ingredient5 { get; set; }
        public string Ingredient6 { get; set; }
        public string Ingredient7 { get; set; }
        public string Ingredient8 { get; set; }
        public string Ingredient9 { get; set; }
        public string Ingredient10 { get; set; }
        public string Ingredient11 { get; set; }
        public string Ingredient12 { get; set; }
        public string Ingredient13 { get; set; }
        public string Ingredient14 { get; set; }
        public string Ingredient15 { get; set; }
        public string Ingredient16 { get; set; }
        public string Ingredient17 { get; set; }
        public string Ingredient18 { get; set; }
        public string Ingredient19 { get; set; }
        public string Ingredient20 { get; set; }
        public string Ingredient21 { get; set; }
        public string Ingredient22 { get; set; }
        public string Ingredient23 { get; set; }
        public string Ingredient24 { get; set; }
        public string Ingredient25 { get; set; }
        public string Ingredient26 { get; set; }
        public string Ingredient27 { get; set; }
        public string Ingredient28 { get; set; }
        public string Ingredient29 { get; set; }
        public string Ingredient30 { get; set; }
        public string Ingredient31 { get; set; }
        public string Ingredient32 { get; set; }
        public string Ingredient33 { get; set; }
        public string Ingredient34 { get; set; }
        public string Ingredient35 { get; set; }
        public string Ingredient36 { get; set; }
        public string Ingredient37 { get; set; }
        public string Ingredient38 { get; set; }
        public string Ingredient39 { get; set; }
        public string Ingredient40 { get; set; }
        public string Ingredient41 { get; set; }
        public string Ingredient42 { get; set; }
        public string Ingredient43 { get; set; }
        public string Ingredient44 { get; set; }
        public string Ingredient45 { get; set; }
        public string Ingredient46 { get; set; }
        public string Ingredient47 { get; set; }
        public string Ingredient48 { get; set; }
        public string Ingredient49 { get; set; }
        public string Ingredient50 { get; set; }
        public string Ingredient51 { get; set; }
        public string Ingredient52 { get; set; }
        public string Ingredient53 { get; set; }
        public string Ingredient54 { get; set; }
        public string Ingredient55 { get; set; }
        public string Ingredient56 { get; set; }
        public string Ingredient57 { get; set; }
        public string Ingredient58 { get; set; }
        public string Ingredient59 { get; set; }
        public string Ingredient60 { get; set; }
        public string Ingredient61 { get; set; }
        public string Ingredient62 { get; set; }
        public string Ingredient63 { get; set; }
        public string Ingredient64 { get; set; }
        public string Ingredient65 { get; set; }
        public string Ingredient66 { get; set; }
        public string Ingredient67 { get; set; }
        public string Ingredient68 { get; set; }
        public string Ingredient69 { get; set; }
        public string Ingredient70 { get; set; }
        public string Ingredient71 { get; set; }
        public string Ingredient72 { get; set; }
        public string Ingredient73 { get; set; }
        public string Ingredient74 { get; set; }
        public string Ingredient75 { get; set; }
        public string Ingredient76 { get; set; }
        public string Ingredient77 { get; set; }
        public string Ingredient78 { get; set; }
        public string Ingredient79 { get; set; }
        public string Ingredient80 { get; set; }
        public string Ingredient81 { get; set; }
        public string Ingredient82 { get; set; }
        public string Ingredient83 { get; set; }
        public string Ingredient84 { get; set; }
        public string Ingredient85 { get; set; }
        public string Ingredient86 { get; set; }
        public string Ingredient87 { get; set; }
        public string Ingredient88 { get; set; }
        public string Ingredient89 { get; set; }
        public string Ingredient90 { get; set; }
        public string Ingredient91 { get; set; }
        public string Ingredient92 { get; set; }
        public string Ingredient93 { get; set; }
        public string Ingredient94 { get; set; }
        public string Ingredient95 { get; set; }
        public string Ingredient96 { get; set; }
        public string Ingredient97 { get; set; }
        public string Ingredient98 { get; set; }
        public string Ingredient99 { get; set; }
        public string Ingredient100 { get; set; }
        public string Ingredient101 { get; set; }
        public string Ingredient102 { get; set; }
        public string Ingredient103 { get; set; }
        public string Ingredient104 { get; set; }
        public string Ingredient105 { get; set; }
        public string Ingredient106 { get; set; }
        public string Ingredient107 { get; set; }
        public string Ingredient108 { get; set; }
        public string Ingredient109 { get; set; }
        public string Ingredient110 { get; set; }
        public string Ingredient111 { get; set; }
        public string Ingredient112 { get; set; }
        public string Ingredient113 { get; set; }
        public string Ingredient114 { get; set; }
        public string Ingredient115 { get; set; }
        public string Ingredient116 { get; set; }
        public string Ingredient117 { get; set; }
        public string Ingredient118 { get; set; }
        public string Ingredient119 { get; set; }
        public string Ingredient120 { get; set; }
        public string Ingredient121 { get; set; }
        public string Ingredient122 { get; set; }
        public string Ingredient123 { get; set; }
        public string Ingredient124 { get; set; }
        public string Ingredient125 { get; set; }
        public string Ingredient126 { get; set; }
        public string Ingredient127 { get; set; }
        public string Ingredient128 { get; set; }
        public string Ingredient129 { get; set; }
        public string Ingredient130 { get; set; }
        public string Ingredient131 { get; set; }
        public string Ingredient132 { get; set; }
        public string Ingredient133 { get; set; }
        public string Ingredient134 { get; set; }
        public string Ingredient135 { get; set; }
        public string Ingredient136 { get; set; }
        public string Ingredient137 { get; set; }
        public string Ingredient138 { get; set; }
        public string Ingredient139 { get; set; }
        public string Ingredient140 { get; set; }
        public string Ingredient141 { get; set; }
        public string Ingredient142 { get; set; }
        public string Ingredient143 { get; set; }
        public string Ingredient144 { get; set; }
        public string Ingredient145 { get; set; }
        public string Ingredient146 { get; set; }
        public string Ingredient147 { get; set; }
        public string Ingredient148 { get; set; }
        public string Ingredient149 { get; set; }
        public string Ingredient150 { get; set; }
        public string Ingredient151 { get; set; }
        public string Ingredient152 { get; set; }
        public string Ingredient153 { get; set; }
        public string Ingredient154 { get; set; }
        public string Ingredient155 { get; set; }
        public string Ingredient156 { get; set; }
        public string Ingredient157 { get; set; }
        public string Ingredient158 { get; set; }
        public string Ingredient159 { get; set; }
        public string Ingredient160 { get; set; }
        public string Ingredient161 { get; set; }
        public string Ingredient162 { get; set; }
        public string Ingredient163 { get; set; }
        public string Ingredient164 { get; set; }
        public string Ingredient165 { get; set; }
        public string Ingredient166 { get; set; }
        public string Ingredient167 { get; set; }
        public string Ingredient168 { get; set; }
        public string Ingredient169 { get; set; }
        public string Ingredient170 { get; set; }
        public string Ingredient171 { get; set; }
        public string Ingredient172 { get; set; }
        public string Ingredient173 { get; set; }
        public string Ingredient174 { get; set; }
        public string Ingredient175 { get; set; }
        public string Ingredient176 { get; set; }
        public string Ingredient177 { get; set; }
        public string Ingredient178 { get; set; }
        public string Ingredient179 { get; set; }
        public string Ingredient180 { get; set; }
        public string Ingredient181 { get; set; }
        public string Ingredient182 { get; set; }
        public string Ingredient183 { get; set; }
        public string Ingredient184 { get; set; }
        public string Ingredient185 { get; set; }
        public string Ingredient186 { get; set; }
        public string Ingredient187 { get; set; }
        public string Ingredient188 { get; set; }
        public string Ingredient189 { get; set; }
        public string Ingredient190 { get; set; }
        public string Ingredient191 { get; set; }
        public string Ingredient192 { get; set; }
        public string Ingredient193 { get; set; }
        public string Ingredient194 { get; set; }
        public string Ingredient195 { get; set; }
        public string Ingredient196 { get; set; }
        public string Ingredient197 { get; set; }
        public string Ingredient198 { get; set; }
        public string Ingredient199 { get; set; }
        public string Ingredient200 { get; set; }
        public string Ingredient201 { get; set; }
        public string Ingredient202 { get; set; }
        public string Ingredient203 { get; set; }
        public string Ingredient204 { get; set; }
        public string Ingredient205 { get; set; }
        public string Ingredient206 { get; set; }
        public string Ingredient207 { get; set; }
        public string Ingredient208 { get; set; }
        public string Ingredient209 { get; set; }
        public string Ingredient210 { get; set; }
        public string Ingredient211 { get; set; }
        public string Ingredient212 { get; set; }
        public string Ingredient213 { get; set; }
        public string Ingredient214 { get; set; }
        public string Ingredient215 { get; set; }
        public string Ingredient216 { get; set; }
        public string Ingredient217 { get; set; }
        public string Ingredient218 { get; set; }
        public string Ingredient219 { get; set; }
        public string Ingredient220 { get; set; }
        public string Ingredient221 { get; set; }
        public string Ingredient222 { get; set; }
        public string Ingredient223 { get; set; }
        public string Ingredient224 { get; set; }
        public string Ingredient225 { get; set; }
        public string Ingredient226 { get; set; }
        public string Ingredient227 { get; set; }
        public string Ingredient228 { get; set; }
        public string Ingredient229 { get; set; }
        public string Ingredient230 { get; set; }
        public string Ingredient231 { get; set; }

        public virtual ICollection<AspNetUsers> AspNetUsers { get; set; }
    }
}
